"""
Dry Run Provider - Returns deterministic valid JSON without making API calls.

This provider is used for testing the orchestration flow without incurring API costs.
It returns valid JSON matching the agent output contract with stub content.
"""

import json
from orchestrator.providers.base import BaseProvider


class DryRunProvider(BaseProvider):
    """
    Provider that returns deterministic valid JSON stubs without making API calls.
    
    Used for testing the full pipeline (prompt rendering, validation, state merging,
    checkpoints, gates) without incurring API costs.
    """
    
    def run(self, prompt: str) -> str:
        """
        Return a deterministic valid JSON stub.
        
        Args:
            prompt: The agent prompt (used to extract agent name if possible)
            
        Returns:
            Valid JSON string matching agent output contract
        """
        # Try to extract agent name from prompt for better stub content
        agent_name = self._extract_agent_name(prompt)
        
        simulated_open_questions = []
        simulated_deliverable_suffix = ""

        if agent_name.lower() == "strategy lead":
            # Simulate Threshold Gate Trigger (simulating > 8 major issues)
            for i in range(10):
                simulated_open_questions.append(f"MAJOR: Simulated specific issue {i}")

        if agent_name.lower() == "quality assurance specialist":
            # Simulate QA Critical Gate Trigger
            simulated_open_questions.append("CRITICAL: Simulated Blocking Issue")
            simulated_deliverable_suffix = "\n\nSeverity: Critical"
            
        # Create deterministic valid JSON response
        deliverable = self._create_stub_deliverable(agent_name) + simulated_deliverable_suffix
        
        response = {
            "deliverable_markdown": deliverable,
            "updated_state": {},
            "open_questions": simulated_open_questions
        }
        
        return json.dumps(response, indent=2)
    
    def _extract_agent_name(self, prompt: str) -> str:
        """
        Attempt to extract agent name from prompt.
        
        Args:
            prompt: The agent prompt
            
        Returns:
            Agent name if found, otherwise "Unknown Agent"
        """
        # Look for common patterns in prompts
        lines = prompt.split('\n')
        
        for line in lines[:50]:  # Check first 50 lines
            line = line.strip()
            
            # Pattern: "# Role: Strategy Lead Agent"
            if line.startswith('# Role:'):
                return line.replace('# Role:', '').strip()
            
            # Pattern: "You are the **Quality Assurance Specialist**"
            if "You are the" in line or "You are a" in line:
                # Remove common prefixes
                cleaned = line.replace('You are the', '').replace('You are a', '').strip()
                # Remove markdown bold/italic
                cleaned = cleaned.replace('**', '').replace('*', '')
                # Take everything before the first comma, period, or newline
                agent_name = cleaned.split(',')[0].split('.')[0].strip()
                if agent_name:
                    return agent_name
        
        return "Unknown Agent"
    
    def _create_stub_deliverable(self, agent_name: str) -> str:
        """
        Create stub deliverable markdown content.
        
        Args:
            agent_name: Name of the agent
            
        Returns:
            Markdown content for the stub deliverable
        """
        return f"""# DRY RUN: {agent_name}

This is a **dry run stub**. No API call was made.

## Purpose

This output was generated by the DryRunProvider to test the orchestration flow
without incurring API costs. This is sample content for testing purposes only.

## What This Tests

- ✅ Prompt rendering and templating
- ✅ JSON extraction and parsing
- ✅ Validation (min chars, stub marker detection)
- ✅ State merging
- ✅ Checkpoint creation
- ✅ Manifest updates
- ✅ Approval gate triggering

## Sample Content

This section contains enough text to pass the minimum character validation threshold.
The dry run provider generates deterministic, valid JSON responses that match the
agent output contract. This allows you to test the entire pipeline flow including
prompt rendering, state management, checkpoints, and approval gates without making
any actual API calls or incurring costs.

## Next Steps

To run with real providers, use:
- `python3 scripts/run_pipeline.py --mode openai`
- `python3 scripts/run_pipeline.py --mode manual`
- `python3 scripts/run_pipeline.py --mode claude_cli`

---

*Generated by DryRunProvider - No API calls made*
"""
